import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
    getCompiler,
    hasCompiler,
    parseKeymap,
    serializeKeymap,
} from '../index'

const seed = readFileSync(
    fileURLToPath(new URL('../../mock/seed.keymap.json', import.meta.url)),
    'utf8',
)
const config = parseKeymap(seed)

describe('keymap compilers', () => {
    it('registers all three targets', () => {
        expect(hasCompiler('zmk')).toBe(true)
        expect(hasCompiler('qmk')).toBe(true)
        expect(hasCompiler('keychron')).toBe(true)
    })

    it('compiles a ZMK .keymap with the expected behaviors', () => {
        const { files, diagnostics } = getCompiler('zmk').compile(config)
        // keymap + physical-layout overlay
        expect(files).toHaveLength(2)
        const keymap = files.find((f) => f.filename.endsWith('.keymap'))!
        const dts = String(keymap.content)
        expect(dts).toContain('compatible = "zmk,keymap"')
        expect(dts).toContain('&kp Q')
        expect(dts).toContain('&kp LC(C)') // "Ctrl+C" combo string
        // the seed's layer-taps set resolve: prefer-hold, so they get a generated
        // hold-tap node (hold-preferred) instead of the global &lt
        expect(dts).toContain('flavor = "hold-preferred"')
        expect(dts).toMatch(/&ht_0 \d+ /) // layer-tap via generated node
        expect(dts).toContain('&mt LSHFT') // plain mod_tap -> global &mt
        expect(dts).toContain('&mo 2') // momentary adjust (index 2)
        expect(dts).toContain('&bt BT_SEL 0')
        expect(dts).toContain('&rgb_ug RGB_TOG')
        expect(dts).toContain('combo_esc')
        expect(dts).toContain('zmk,behavior-macro')
        expect(dts).toContain('zmk,behavior-tap-dance')
        expect(dts).toContain('&inc_dec_kp') // encoder
        // per_key lighting is unsupported on ZMK -> warn
        expect(
            diagnostics.some(
                (d) => d.level === 'warn' && /per_key/.test(d.message),
            ),
        ).toBe(true)
    })

    it('compiles a QMK keymap.c with the expected keycodes', () => {
        const { files, diagnostics } = getCompiler('qmk').compile(config)
        const c = String(files[0].content)
        expect(files[0].filename).toBe('keymap.c')
        expect(c).toContain('const uint16_t PROGMEM keymaps')
        expect(c).toContain('MO(2)')
        expect(c).toContain('LT(1,')
        expect(c).toContain('LSFT_T(')
        expect(c).toContain('LCTL(') // Ctrl+C
        expect(c).toContain('RGB_MOD') // per_key effect_next is fine on QMK
        // bluetooth output has no standard QMK keycode -> warn
        expect(
            diagnostics.some(
                (d) =>
                    d.level === 'warn' && /output "bluetooth"/.test(d.message),
            ),
        ).toBe(true)
    })

    it('Keychron allows bluetooth output (no output warning)', () => {
        const { diagnostics } = getCompiler('keychron').compile(config)
        expect(
            diagnostics.some((d) => /output "bluetooth"/.test(d.message)),
        ).toBe(false)
    })

    it('emits a ZMK physical-layout .overlay from the geometry', () => {
        const { files } = getCompiler('zmk').compile(config)
        const overlay = files.find((f) => f.filename.endsWith('.overlay'))!
        const o = String(overlay.content)
        expect(o).toContain('#include <physical_layouts.dtsi>')
        expect(o).toContain('compatible = "zmk,physical-layout"')
        expect(o).toContain('&key_physical_attrs')
        // 36 keys -> 36 key_physical_attrs entries
        expect(o.match(/&key_physical_attrs/g)).toHaveLength(36)
    })

    it('emits a geometry-derived matrix-transform wired to the physical-layout', () => {
        const { files, diagnostics } = getCompiler('zmk').compile(config)
        const overlay = files.find((f) => f.filename.endsWith('.overlay'))!
        const o = String(overlay.content)
        expect(o).toContain('#include <dt-bindings/zmk/matrix_transform.h>')
        expect(o).toContain('compatible = "zmk,matrix-transform"')
        expect(o).toContain('transform = <&default_transform>;')
        // one RC() per key, in keymap order
        expect(o.match(/RC\(\d+,\d+\)/g)).toHaveLength(36)
        // honest about the derivation
        expect(
            diagnostics.some((d) => /matrix-transform RC/.test(d.message)),
        ).toBe(true)
    })

    it('lists non-generated board hardware as a checklist in both files', () => {
        const { files } = getCompiler('zmk').compile(config)
        const overlay = String(
            files.find((f) => f.filename.endsWith('.overlay'))!.content,
        )
        expect(overlay).toContain('NOT GENERATED by remappr')
        expect(overlay).toContain('kscan')
        expect(overlay).toContain('pinctrl')
        const keymap = String(
            files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(keymap).toContain('NOT GENERATED')
    })

    // pattern-check: skip — regression test data for the per-firmware fallback
    it('drops actions a firmware has no handler for to its own no-op', () => {
        // layer_lock + peripheral are §5.2 Remappr-firmware-only kinds: neither the
        // ZMK nor the QMK handler table carries them, so each compiler must warn +
        // emit its own no-op token (its capability = handler presence) rather than
        // a real binding.
        const cfg = parseKeymap(`{
            "schemaVersion": 1, "kind": "remappr.keymap",
            "meta": { "name": "RO", "target": "zmk" },
            "keyboard": { "id": "ro", "name": "RO",
                "keys": [{"x":0,"y":0},{"x":1,"y":0}] },
            "layers": [
                { "name": "base", "bindings": [
                    { "type": "layer_lock" },
                    { "type": "peripheral", "kind": "encoder", "code": 3 }
                ] },
                { "name": "fn", "bindings": [
                    { "type": "transparent" }, { "type": "transparent" }
                ] }
            ]
        }`)

        const zmk = getCompiler('zmk').compile(cfg)
        const keymap = String(
            zmk.files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(keymap).toContain('&none')
        for (const t of ['layer_lock', 'peripheral']) {
            expect(
                zmk.diagnostics.some(
                    (d) =>
                        d.level === 'warn' &&
                        d.message === `"${t}" has no ZMK binding; emitted &none`,
                ),
            ).toBe(true)
        }

        const qmk = getCompiler('qmk').compile(cfg)
        expect(String(qmk.files[0].content)).toContain('KC_NO')
        for (const t of ['layer_lock', 'peripheral']) {
            expect(
                qmk.diagnostics.some(
                    (d) =>
                        d.level === 'warn' &&
                        d.message === `"${t}" has no QMK keycode; emitted KC_NO`,
                ),
            ).toBe(true)
        }
    })
})

// A config exercising every behavior added for real-ZMK-config parity.
const EXTRA = `{
    "schemaVersion": 1,
    "kind": "remappr.keymap",
    "meta": { "name": "Extra", "target": null },
    "keyboard": { "id": "extra", "name": "Extra", "keys": [
        {"x":0,"y":0},{"x":1,"y":0},{"x":2,"y":0},{"x":3,"y":0},
        {"x":0,"y":1},{"x":1,"y":1},{"x":2,"y":1},{"x":3,"y":1},
        {"x":0,"y":2},{"x":1,"y":2},{"x":2,"y":2},{"x":3,"y":2},
        {"x":0,"y":3},{"x":1,"y":3},{"x":2,"y":3},{"x":3,"y":3}
    ] },
    "layers": [{ "name": "base", "bindings": [
        { "type": "key_toggle", "key": "CAPSLOCK" },
        { "type": "key_repeat" },
        { "type": "grave_escape" },
        { "type": "ext_power", "action": "toggle" },
        { "type": "mouse_key", "button": "left" },
        { "type": "mouse_move", "direction": "right" },
        { "type": "mouse_scroll", "direction": "down" },
        { "type": "studio_unlock" },
        { "type": "soft_off" },
        { "type": "output", "action": "bluetooth_next" },
        { "type": "output", "action": "bluetooth_prev" },
        { "type": "output", "action": "toggle" },
        { "type": "macro", "ref": "m_param", "param": "C" },
        { "type": "transparent" },
        { "type": "transparent" },
        { "type": "transparent" }
    ] }],
    "macros": [{
        "id": "m_param", "params": 1,
        "steps": [
            { "type": "press", "key": "LCTRL" },
            { "type": "param" },
            { "type": "pause_for_release" },
            { "type": "release", "key": "LCTRL" }
        ]
    }]
}`

describe('ZMK parity behaviors', () => {
    const dts = String(
        getCompiler('zmk').compile(parseKeymap(EXTRA)).files[0].content,
    )

    it('emits every new behavior token', () => {
        expect(dts).toContain('&kt CAPS')
        expect(dts).toContain('&key_repeat')
        expect(dts).toContain('&gresc')
        expect(dts).toContain('&ext_power EP_TOG')
        expect(dts).toContain('&mkp MB1')
        expect(dts).toContain('&mmv MOVE_RIGHT')
        expect(dts).toContain('&msc SCRL_DOWN')
        expect(dts).toContain('&studio_unlock')
        expect(dts).toContain('&soft_off')
        expect(dts).toContain('&bt BT_NXT')
        expect(dts).toContain('&bt BT_PRV')
        expect(dts).toContain('&out OUT_TOG')
        expect(dts).toContain('#include <dt-bindings/zmk/pointing.h>')
    })

    it('emits a one-param macro and its parametrized call', () => {
        expect(dts).toContain('compatible = "zmk,behavior-macro-one-param"')
        expect(dts).toContain('#binding-cells = <1>')
        expect(dts).toContain('&macro_param_1to1')
        expect(dts).toContain('&macro_pause_for_release')
        expect(dts).toContain('&m_param C')
    })

    it('QMK maps mouse keys and degrades ZMK-only behaviors', () => {
        const c = String(
            getCompiler('qmk').compile(parseKeymap(EXTRA)).files[0].content,
        )
        expect(c).toContain('KC_MS_BTN1')
        expect(c).toContain('KC_MS_RIGHT')
        expect(c).toContain('QK_GESC')
        expect(c).toContain('QK_REP')
    })
})

const COND = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "Cond", "target": "zmk" },
    "keyboard": { "id": "c", "name": "C", "keys": [{"x":0,"y":0}] },
    "layers": [
        { "name": "base", "bindings": ["A"] },
        { "name": "lower", "bindings": ["B"] },
        { "name": "raise", "bindings": ["C"] },
        { "name": "adjust", "bindings": ["D"] }
    ],
    "conditionalLayers": [
        { "ifLayers": ["lower", "raise"], "thenLayer": "adjust" }
    ]
}`

describe('conditional layers', () => {
    it('round-trips through parseKeymap → serialize', () => {
        const cfg = parseKeymap(COND)
        expect(cfg.conditionalLayers).toEqual([
            { ifLayers: ['lower', 'raise'], thenLayer: 'adjust' },
        ])
        const reparsed = parseKeymap(serializeKeymap(cfg))
        expect(reparsed.conditionalLayers).toEqual(cfg.conditionalLayers)
    })

    it('emits a zmk,conditional-layers node with layer indices', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(COND))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('compatible = "zmk,conditional-layers"')
        expect(dts).toContain('if-layers = <1 2>;') // lower=1, raise=2
        expect(dts).toContain('then-layer = <3>;') // adjust=3
    })

    it('QMK warns conditional layers are not generated', () => {
        const { diagnostics } = getCompiler('qmk').compile(parseKeymap(COND))
        expect(
            diagnostics.some((d) => /conditional layers/.test(d.message)),
        ).toBe(true)
    })

    it('rejects a conditional layer referencing an unknown layer', () => {
        const bad = COND.replace('"adjust" }', '"nope" }')
        expect(() => parseKeymap(bad)).toThrow(/unknown layer/)
    })
})

const ENC = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "Enc", "target": "zmk" },
    "keyboard": { "id": "e", "name": "E", "keys": [{"x":0,"y":0}],
        "encoders": [{"x":0,"y":0},{"x":1,"y":0}] },
    "layers": [{ "name": "base", "bindings": ["A"], "encoders": [
        { "cw": "Up", "ccw": "Down" },
        { "cw": { "type": "lighting", "target": "underglow", "action": "brightness_up" },
          "ccw": { "type": "lighting", "target": "underglow", "action": "brightness_down" } }
    ] }]
}`

describe('encoders / sensor-rotate', () => {
    it('emits inc_dec_kp for keypress pairs and a sensor-rotate node otherwise', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(ENC))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        // keypress encoder → inc_dec_kp
        expect(dts).toContain('&inc_dec_kp')
        // non-keypress encoder → generated sensor-rotate behavior node
        expect(dts).toContain('compatible = "zmk,behavior-sensor-rotate"')
        expect(dts).toContain('sr_0_1: sr_0_1 {')
        expect(dts).toContain('&rgb_ug RGB_BRI')
        // layer references both in sensor-bindings
        expect(dts).toMatch(/sensor-bindings = <&inc_dec_kp[^;]*&sr_0_1>;/)
    })

    it('QMK emits encoder_map (guarded) + warns to enable it', () => {
        const { files, diagnostics } = getCompiler('qmk').compile(
            parseKeymap(ENC),
        )
        const c = String(files.find((f) => f.filename === 'keymap.c')!.content)
        expect(c).toContain('#ifdef ENCODER_MAP_ENABLE')
        expect(c).toContain('encoder_map[][NUM_ENCODERS][2]')
        expect(c).toContain('ENCODER_CCW_CW(')
        expect(diagnostics.some((d) => /encoder/.test(d.message))).toBe(true)
    })

    it('QMK encoder_map sources per-key encoderBindings too', () => {
        const c = String(
            getCompiler('qmk')
                .compile(parseKeymap(ENC_PERKEY))
                .files.find((f) => f.filename === 'keymap.c')!.content,
        )
        expect(c).toContain('encoder_map[][NUM_ENCODERS][2]')
        // two encoders → two ENCODER_CCW_CW cells on the base layer
        expect(c).toMatch(/\[0\] = \{ ENCODER_CCW_CW\(.*ENCODER_CCW_CW\(.*\},/)
    })

    it('emits sensor-bindings from per-key encoderBindings (element model)', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(ENC_PERKEY))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        // key 0 (keypress pair) → inc_dec_kp; key 1 (lighting) → sensor-rotate
        expect(dts).toContain('&inc_dec_kp')
        expect(dts).toContain('sr_0_k1: sr_0_k1 {')
        expect(dts).toContain('&rgb_ug RGB_BRI')
        // both encoders appear in the layer's sensor-bindings, key-index ordered
        expect(dts).toMatch(/sensor-bindings = <&inc_dec_kp[^;]*&sr_0_k1>;/)
    })
})

const SLIDER = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "Sld", "target": "zmk" },
    "keyboard": { "id": "s", "name": "S", "keys": [
        {"x":0,"y":0,"element":"slider","pin":"GP29"},
        {"x":1,"y":0}
    ] },
    "layers": [{ "name": "base", "bindings": ["A","B"], "sliderBindings": {
        "0": { "map": "volume", "min": 0, "max": 100 }
    } }]
}`

const SLIDER_CUSTOM = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "SldC", "target": "zmk" },
    "keyboard": { "id": "s", "name": "S", "keys": [
        {"x":0,"y":0,"element":"slider"}, {"x":1,"y":0}
    ] },
    "layers": [{ "name": "base", "bindings": ["A","B"], "sliderBindings": {
        "0": { "map": "custom", "action": "Up" }
    } }]
}`

describe('sliders / analog input', () => {
    it('ZMK emits a NOT-GENERATED slider guidance block + warns', () => {
        const { files, diagnostics } = getCompiler('zmk').compile(
            parseKeymap(SLIDER),
        )
        const dts = String(
            files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('SLIDER / ANALOG INPUT — NOT GENERATED')
        // captured value-map appears: key index, map + range, ADC pin
        expect(dts).toContain('slider @ key 0 (ADC pin GP29)')
        expect(dts).toMatch(/base: volume \[0\.\.100\]/)
        expect(diagnostics.some((d) => /analog|slider/i.test(d.message))).toBe(
            true,
        )
    })

    it('ZMK inlines a custom slider action into the guidance', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(SLIDER_CUSTOM))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toMatch(/base: custom .*→ &kp UP/)
    })

    it('QMK emits an analog scaffold + warns', () => {
        const { files, diagnostics } = getCompiler('qmk').compile(
            parseKeymap(SLIDER),
        )
        const c = String(files.find((f) => f.filename === 'keymap.c')!.content)
        expect(c).toContain('SLIDER / ANALOG INPUT')
        expect(c).toContain('analogReadPin')
        expect(c).toMatch(/base: volume \[0\.\.100\]/)
        expect(diagnostics.some((d) => /analog|slider/i.test(d.message))).toBe(
            true,
        )
    })

    it('no slider element → no guidance block, no warn', () => {
        const { files, diagnostics } = getCompiler('zmk').compile(config)
        const dts = String(
            files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).not.toContain('SLIDER / ANALOG INPUT')
        expect(diagnostics.some((d) => /slider/i.test(d.message))).toBe(false)
    })
})

const ENC_PERKEY = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "EncPK", "target": "zmk" },
    "keyboard": { "id": "e", "name": "E", "keys": [
        {"x":0,"y":0,"element":"encoder"},
        {"x":1,"y":0,"element":"encoder"}
    ] },
    "layers": [{ "name": "base", "bindings": ["A","B"], "encoderBindings": {
        "0": { "cw": "Up", "ccw": "Down" },
        "1": { "cw": { "type": "lighting", "target": "underglow", "action": "brightness_up" },
               "ccw": { "type": "lighting", "target": "underglow", "action": "brightness_down" } }
    } }]
}`

const TAILS = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "Tails", "target": "zmk" },
    "keyboard": { "id": "t", "name": "T", "keys": [
        {"x":0,"y":0},{"x":1,"y":0},{"x":2,"y":0},{"x":3,"y":0}
    ] },
    "layers": [{ "name": "base", "bindings": [
        { "type": "output", "action": "bluetooth_disconnect", "profile": 1 },
        { "type": "output", "action": "none" },
        { "type": "lighting", "target": "backlight", "action": "cycle" },
        { "type": "macro", "ref": "swap" }
    ] }],
    "macros": [{
        "id": "swap", "params": 2,
        "steps": [
            { "type": "param", "from": 2, "to": 1 },
            { "type": "tap_time", "ms": 20 },
            { "type": "param", "from": 1, "to": 1 }
        ]
    }]
}`

describe('enum tails + 2-param macros', () => {
    it('emits BT_DISC, OUT_NONE, BL_CYCLE', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(TAILS))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('&bt BT_DISC 1')
        expect(dts).toContain('&out OUT_NONE')
        expect(dts).toContain('&bl BL_CYCLE')
    })

    it('emits a two-param macro with param forwarding and tap_time', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(TAILS))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('compatible = "zmk,behavior-macro-two-param"')
        expect(dts).toContain('#binding-cells = <2>')
        expect(dts).toContain('&macro_param_2to1')
        expect(dts).toContain('&macro_tap_time 20')
    })

    it('round-trips through serialize', () => {
        const cfg = parseKeymap(TAILS)
        const re = parseKeymap(serializeKeymap(cfg))
        expect(re.macros?.[0].params).toBe(2)
        expect(re.macros?.[0].steps).toContainEqual({
            type: 'param',
            from: 2,
            to: 1,
        })
    })
})

const MORPH = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "Morph", "target": "zmk" },
    "keyboard": { "id": "m", "name": "M", "keys": [{"x":0,"y":0}] },
    "layers": [{ "name": "base", "bindings": [{ "type": "mod_morph", "ref": "dot_colon" }] }],
    "modMorphs": [{
        "id": "dot_colon",
        "mods": ["LEFT_SHIFT", "RIGHT_SHIFT"],
        "keepMods": ["LEFT_GUI"],
        "bindings": [".", ":"]
    }]
}`

describe('mod-morph', () => {
    it('emits a zmk,behavior-mod-morph node with mod flags', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(MORPH))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('compatible = "zmk,behavior-mod-morph"')
        expect(dts).toContain('mods = <(MOD_LSFT|MOD_RSFT)>;')
        expect(dts).toContain('keep-mods = <(MOD_LGUI)>;')
        expect(dts).toContain('&dot_colon') // reference in the layer
    })

    it('QMK degrades mod-morph with a warning', () => {
        const { diagnostics } = getCompiler('qmk').compile(parseKeymap(MORPH))
        expect(diagnostics.some((d) => /mod-morph/.test(d.message))).toBe(true)
    })

    it('rejects a reference to an unknown mod-morph', () => {
        const bad = MORPH.replace('"ref": "dot_colon"', '"ref": "nope"')
        expect(() => parseKeymap(bad)).toThrow(/unknown mod-morph/)
    })
})

const HT_INLINE = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "HT", "target": "zmk" },
    "keyboard": { "id": "h", "name": "H", "keys": [{"x":0,"y":0},{"x":1,"y":0}] },
    "layers": [{ "name": "base", "bindings": [
        { "type": "mod_tap", "tap": "A", "mod": "LEFT_SHIFT", "flavor": "balanced", "tappingTermMs": 200 },
        { "type": "mod_tap", "tap": "B", "mod": "LEFT_SHIFT", "flavor": "balanced", "tappingTermMs": 200 }
    ] }]
}`

const HT_DEF = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "HTD", "target": "zmk" },
    "keyboard": { "id": "hd", "name": "HD", "keys": [{"x":0,"y":0}] },
    "layers": [{ "name": "base", "bindings": [
        { "type": "hold_tap", "ref": "hm", "holdParam": "LEFT_SHIFT", "tapParam": "A" }
    ] }],
    "holdTaps": [{
        "id": "hm", "flavor": "tap-preferred", "tappingTermMs": 280,
        "holdTriggerKeyPositions": [1, 2], "retroTap": true,
        "bindings": ["&kp", "&kp"]
    }]
}`

describe('custom hold-tap', () => {
    it('generates a hold-tap node for a tap_hold with flavor/timing and dedups it', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(HT_INLINE))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('compatible = "zmk,behavior-hold-tap"')
        expect(dts).toContain('flavor = "balanced";')
        expect(dts).toContain('tapping-term-ms = <200>;')
        // both identical tap_holds share one generated node (ht_0), no ht_1
        expect(dts).toContain('ht_0:')
        expect(dts).not.toContain('ht_1:')
        expect((dts.match(/&ht_0 /g) ?? []).length).toBe(2)
        // and it is NOT the global &mt
        expect(dts).not.toMatch(/&mt LSHFT A/)
    })

    it('plain tap-holds (no flavor/timing) still use global &mt/&lt', () => {
        const plain = `{
            "schemaVersion": 1, "kind": "remappr.keymap",
            "meta": { "name": "P", "target": "zmk" },
            "keyboard": { "id": "p", "name": "P", "keys": [{"x":0,"y":0},{"x":1,"y":0}] },
            "layers": [{ "name": "base", "bindings": [
                { "type": "mod_tap", "tap": "A", "mod": "LEFT_SHIFT" },
                { "type": "layer_tap", "tap": "SPACE", "layer": "base" }
            ] }]
        }`
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(plain))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('&mt LSHFT A')
        expect(dts).toContain('&lt 0 SPACE')
        expect(dts).not.toContain('zmk,behavior-hold-tap')
    })

    it('emits a user-defined hold-tap node and references it', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(HT_DEF))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('hm: hm {')
        expect(dts).toContain('compatible = "zmk,behavior-hold-tap"')
        expect(dts).toContain('flavor = "tap-preferred";')
        expect(dts).toContain('hold-trigger-key-positions = <1 2>;')
        expect(dts).toContain('retro-tap;')
        expect(dts).toMatch(/&hm \S+ \S+/) // reference with two params
    })

    it('rejects a reference to an unknown hold-tap', () => {
        const bad = HT_DEF.replace('"ref": "hm"', '"ref": "nope"')
        expect(() => parseKeymap(bad)).toThrow(/unknown hold-tap/)
    })

    it('QMK degrades a custom hold-tap reference with a warning', () => {
        const { diagnostics } = getCompiler('qmk').compile(parseKeymap(HT_DEF))
        expect(diagnostics.some((d) => /hold-tap/.test(d.message))).toBe(true)
    })
})

describe('board hardware (kscan + electrical transform)', () => {
    const HW_MATRIX = `{
        "schemaVersion": 1, "kind": "remappr.keymap",
        "meta": { "name": "HW", "target": "zmk" },
        "keyboard": {
            "id": "hw", "name": "HW",
            "keys": [{"x":0,"y":0},{"x":1,"y":0}],
            "hardware": {
                "board": "nice_nano_v2",
                "kscan": {
                    "type": "matrix",
                    "diodeDirection": "col2row",
                    "rowGpios": ["&gpio0 5 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)"],
                    "colGpios": ["&gpio0 6 GPIO_ACTIVE_HIGH", "&gpio0 7 GPIO_ACTIVE_HIGH"],
                    "debouncePressMs": 5,
                    "debounceReleaseMs": 5
                },
                "transform": { "rows": 1, "columns": 2, "map": [[0,0],[0,1]] }
            }
        },
        "layers": [{ "name": "base", "bindings": ["A", "B"] }]
    }`

    const HW_DIRECT = `{
        "schemaVersion": 1, "kind": "remappr.keymap",
        "meta": { "name": "HD", "target": "zmk" },
        "keyboard": {
            "id": "hd", "name": "HD",
            "keys": [{"x":0,"y":0},{"x":1,"y":0}],
            "hardware": {
                "kscan": {
                    "type": "direct",
                    "inputGpios": [
                        "&gpio0 2 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)",
                        "&gpio0 3 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)"
                    ]
                }
            }
        },
        "layers": [{ "name": "base", "bindings": ["A", "B"] }]
    }`

    const overlayOf = (src: string): string =>
        String(
            getCompiler('zmk')
                .compile(parseKeymap(src))
                .files.find((f) => f.filename.endsWith('.overlay'))!.content,
        )

    it('emits a real matrix kscan + chosen + electrical transform', () => {
        const { diagnostics } = getCompiler('zmk').compile(
            parseKeymap(HW_MATRIX),
        )
        const o = overlayOf(HW_MATRIX)
        expect(o).toContain('compatible = "zmk,kscan-gpio-matrix"')
        expect(o).toContain('diode-direction = "col2row";')
        expect(o).toContain('<&gpio0 5 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>')
        expect(o).toContain('debounce-press-ms = <5>;')
        expect(o).toContain('#include <dt-bindings/gpio/gpio.h>')
        // chosen wiring
        expect(o).toContain('zmk,kscan = <&kscan0>;')
        expect(o).toContain('zmk,physical-layout = <&physical_layout_default>;')
        // electrical (not geometry) transform — no derivation warning
        expect(o).toContain('From the board electrical wiring')
        expect(o).toContain('Target board: nice_nano_v2.')
        expect(o.match(/RC\(\d+,\d+\)/g)).toHaveLength(2)
        expect(
            diagnostics.some((d) => /matrix-transform RC/.test(d.message)),
        ).toBe(false)
    })

    it('emits a direct kscan and shrinks the NOT-GENERATED checklist', () => {
        const o = overlayOf(HW_DIRECT)
        expect(o).toContain('compatible = "zmk,kscan-gpio-direct"')
        expect(o).toContain('<&gpio0 2 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>')
        expect(o).toContain('zmk,kscan = <&kscan0>;')
        // checklist no longer lists kscan/chosen, but still flags pinctrl/LEDs
        expect(o).toContain('NOT GENERATED by remappr')
        expect(o).toContain('pinctrl')
        expect(o).not.toMatch(/•\s+kscan\b/)
        expect(o).not.toMatch(/•\s+chosen\b/)
    })

    it('keymap-only configs (no hardware) keep the full checklist + derived transform', () => {
        const o = overlayOf(`{
            "schemaVersion": 1, "kind": "remappr.keymap",
            "meta": { "name": "K", "target": "zmk" },
            "keyboard": { "id": "k", "name": "K", "keys": [{"x":0,"y":0},{"x":1,"y":0}] },
            "layers": [{ "name": "base", "bindings": ["A", "B"] }]
        }`)
        expect(o).not.toContain('zmk,kscan-gpio')
        expect(o).toMatch(/•\s+kscan\b/)
        expect(o).toContain('DERIVED from key geometry')
    })

    it('round-trips hardware through serialize → parse', () => {
        const config = parseKeymap(HW_MATRIX)
        const reparsed = parseKeymap(serializeKeymap(config))
        expect(reparsed.keyboard.hardware).toEqual(config.keyboard.hardware)
    })

    it('rejects a transform whose map count does not match the key count', () => {
        const bad = HW_MATRIX.replace('"map": [[0,0],[0,1]]', '"map": [[0,0]]')
        expect(() => parseKeymap(bad)).toThrow(/matrix-transform map has 1/)
    })

    it('rejects a transform RC() index out of the declared matrix range', () => {
        const bad = HW_MATRIX.replace(
            '"map": [[0,0],[0,1]]',
            '"map": [[0,0],[0,5]]',
        )
        expect(() => parseKeymap(bad)).toThrow(/out of range/)
    })

    it('rejects GPIO counts that disagree with the transform size', () => {
        const bad = HW_MATRIX.replace(
            '"rowGpios": ["&gpio0 5 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)"]',
            '"rowGpios": ["&gpio0 5 X", "&gpio0 8 X"]',
        )
        expect(() => parseKeymap(bad)).toThrow(/row GPIOs/)
    })

    it('rejects a direct kscan whose input count does not match the keys', () => {
        const bad = HW_DIRECT.replace(
            ',\n                        "&gpio0 3 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)"',
            '',
        )
        expect(() => parseKeymap(bad)).toThrow(/input GPIOs/)
    })
})

describe('value-carrying lighting (HSB / BL_SET)', () => {
    const LIGHT = `{
        "schemaVersion": 1, "kind": "remappr.keymap",
        "meta": { "name": "L", "target": "zmk" },
        "keyboard": { "id": "l", "name": "L", "keys": [{"x":0,"y":0},{"x":1,"y":0}] },
        "layers": [{ "name": "base", "bindings": [
            { "type": "lighting", "target": "underglow", "action": "color", "hue": 120, "saturation": 100, "brightness": 80 },
            { "type": "lighting", "target": "backlight", "action": "set", "level": 50 }
        ] }]
    }`

    it('ZMK emits RGB_COLOR_HSB and BL_SET with their values', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(LIGHT))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('&rgb_ug RGB_COLOR_HSB(120,100,80)')
        expect(dts).toContain('&bl BL_SET 50')
    })

    it('round-trips the values through serialize → parse', () => {
        const config = parseKeymap(LIGHT)
        const reparsed = parseKeymap(serializeKeymap(config))
        expect(reparsed.layers[0].bindings).toEqual(config.layers[0].bindings)
    })

    it('rejects "color" without a full HSB triple', () => {
        const bad = LIGHT.replace('"hue": 120, ', '')
        expect(() => parseKeymap(bad)).toThrow(/requires hue, saturation/)
    })

    it('rejects "set" without a level', () => {
        const bad = LIGHT.replace(', "level": 50', '')
        expect(() => parseKeymap(bad)).toThrow(/requires a level/)
    })

    it('QMK degrades color/set with warnings', () => {
        const { diagnostics } = getCompiler('qmk').compile(parseKeymap(LIGHT))
        expect(diagnostics.some((d) => d.level === 'warn')).toBe(true)
    })
})
