// Pattern check: no GoF pattern (-) — rejected — pure repo-skeleton file
// generators wrapping the existing compiler Strategy; string templating, no
// abstraction.
//
// Builds a ready-to-push firmware PROJECT bundle (not just the keymap files):
// the full repo skeleton + CI workflow + README the user can drop on GitHub
// (Actions builds the binary) or build locally. This is the Phase-1 zero-dep
// fallback — it never needs the cloud. The keymap/overlay/keymap.c come straight
// from the compilers (getCompiler); this module adds the surrounding scaffolding.

import type { ExportedFile } from '../types'
import type { Diagnostic } from './diagnostics'
import { getCompiler } from './compiler'
import {
    resolveController,
    zmkSplitShields,
    type ZmkSplitShields,
} from './controller'
import { dtsString } from './compilers/zmk/maps'
import { buildQmkKeyboardJson } from './compilers/qmkKeyboardJson'
import { buildViaJson } from './compilers/viaJson'
import { buildVialJson } from './compilers/vialJson'
import {
    deriveQmkConfigH,
    deriveQmkRulesMk,
    deriveZmkConf,
} from './firmwareConf'
import type { ConfigKeymap, Target } from './types'

export interface ProjectBundle {
    /** Files whose `filename` is the path INSIDE the archive. */
    files: ExportedFile[]
    diagnostics: Diagnostic[]
    /** Suggested archive base name (no extension). */
    rootName: string
}

const sanitize = (s: string): string =>
    s
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '') || 'remappr'

const asText = (c: string | Uint8Array): string =>
    typeof c === 'string' ? c : new TextDecoder().decode(c)

const text = (filename: string, content: string): ExportedFile => ({
    filename,
    mime: 'text/plain',
    content,
})

/* ── ZMK ─────────────────────────────────────────────────────────────────── */

const ZMK_BUILD_WORKFLOW = [
    `name: Build ZMK firmware`,
    `on: [push, pull_request, workflow_dispatch]`,
    `jobs:`,
    `  build:`,
    `    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main`,
    ``,
].join('\n')

const ZMK_WEST_YML = [
    `manifest:`,
    `  remotes:`,
    `    - name: zmkfirmware`,
    `      url-base: https://github.com/zmkfirmware`,
    `  projects:`,
    `    - name: zmk`,
    `      remote: zmkfirmware`,
    `      revision: main`,
    `      import: app/west.yml`,
    `  self:`,
    `    path: config`,
    ``,
].join('\n')

// pattern-check: skip pure string-template generators for a shield dir, no abstraction
// ZMK shield-scaffold generators (Kconfig + metadata) mirroring a real shield dir.
// `ZMK_KEYBOARD_NAME` is capped at 16 chars by ZMK; truncate the display name.
const kconfigShield = (SHIELD: string): string =>
    [
        `config SHIELD_${SHIELD}`,
        `    def_bool $(shields_list_contains, ${SHIELD})`,
        ``,
    ].join('\n')

const kconfigDefconfig = (SHIELD: string, name: string): string =>
    [
        `if SHIELD_${SHIELD}`,
        ``,
        `config ZMK_KEYBOARD_NAME`,
        `\tdefault "${dtsString(name.slice(0, 16))}"`,
        ``,
        `endif # SHIELD_${SHIELD}`,
        ``,
    ].join('\n')

const shieldMetaYml = (id: string, name: string): string =>
    [`file_format: "1"`, `id: ${id}`, `name: ${name}`, `type: shield`, ``].join(
        '\n',
    )

function zmkBundle(config: ConfigKeymap): ProjectBundle {
    const split = zmkSplitShields(config)
    if (split) return zmkSplitBundle(config, split)
    const ctrl = resolveController(config)
    const shieldId = sanitize(
        ctrl.shield || config.keyboard.id || config.meta.name,
    )
    const SHIELD = shieldId.toUpperCase()
    const board = ctrl.board || 'YOUR_BOARD'
    const { files: compiled, diagnostics } = getCompiler('zmk').compile(config)
    const keymap = compiled.find((f) => f.filename.endsWith('.keymap'))
    const overlay = compiled.find((f) => f.filename.endsWith('.overlay'))

    // The custom shield lives in its own dir so the overlay/Kconfig describe a
    // self-contained board ZMK can discover (config/boards/shields/<id>/), exactly
    // like a hand-written zmk-config. The build matrix + manifest sit at the root.
    const shieldDir = `config/boards/shields/${shieldId}`

    const buildYaml = [
        `include:`,
        `  - board: ${board}`,
        `    shield: ${SHIELD}`,
        ``,
    ].join('\n')

    const readme = [
        `# ${config.meta.name} — ZMK config`,
        ``,
        `Generated by remappr. This is a ready-to-build \`zmk-config\` repo with a`,
        `self-contained shield under \`${shieldDir}/\`.`,
        ``,
        `## Build in the cloud (no toolchain)`,
        `1. Create a new GitHub repository and push these files.`,
        `2. The included workflow (\`.github/workflows/build.yml\`) builds on every push.`,
        `3. Open the Actions run → download the \`firmware\` artifact (\`.uf2\`).`,
        ``,
        `## Build locally`,
        `\`\`\`sh`,
        `west init -l config && west update`,
        `west build -s zmk/app -b ${board} -- -DSHIELD=${SHIELD} -DZMK_CONFIG="$(pwd)/config"`,
        `\`\`\``,
        ``,
        `## Notes`,
        `- Set \`board\` in \`build.yaml\` to your actual controller (currently \`${board}\`).`,
        `- \`${shieldDir}/${SHIELD}.overlay\` holds the kscan + matrix-transform +`,
        `  physical-layout; \`${SHIELD}.keymap\` the bindings; \`${SHIELD}.conf\` the`,
        `  Kconfig flags. \`Kconfig.shield\` / \`Kconfig.defconfig\` register the shield.`,
        `- Re-check the matrix-transform \`RC()\` map against your real kscan wiring —`,
        `  remappr derives it from physical key position, not the electrical matrix.`,
        ``,
    ].join('\n')

    const files: ExportedFile[] = [
        text(
            `${shieldDir}/${SHIELD}.keymap`,
            keymap ? asText(keymap.content) : '',
        ),
        text(`${shieldDir}/${SHIELD}.conf`, deriveZmkConf(config)),
        text(`${shieldDir}/Kconfig.shield`, kconfigShield(SHIELD)),
        text(
            `${shieldDir}/Kconfig.defconfig`,
            kconfigDefconfig(SHIELD, config.meta.name),
        ),
        text(
            `${shieldDir}/${shieldId}.zmk.yml`,
            shieldMetaYml(shieldId, config.meta.name),
        ),
    ]
    if (overlay)
        files.push(
            text(`${shieldDir}/${SHIELD}.overlay`, asText(overlay.content)),
        )
    files.push(
        text(`config/west.yml`, ZMK_WEST_YML),
        text(`build.yaml`, buildYaml),
        text(`.github/workflows/build.yml`, ZMK_BUILD_WORKFLOW),
        text(`README.md`, readme),
    )

    return { files, diagnostics, rootName: `${shieldId}-zmk-config` }
}

// pattern-check: skip split-shield Kconfig templates + bundle assembly, no abstraction
// Kconfig.shield registering both half symbols, keyed by the lowercase shield names.
const kconfigShieldSplit = (s: ZmkSplitShields): string =>
    [
        `config SHIELD_${s.left.toUpperCase()}`,
        `    def_bool $(shields_list_contains, ${s.left})`,
        ``,
        `config SHIELD_${s.right.toUpperCase()}`,
        `    def_bool $(shields_list_contains, ${s.right})`,
        ``,
    ].join('\n')

// Kconfig.defconfig: name + central role on the left half, split mode on both.
const kconfigDefconfigSplit = (s: ZmkSplitShields, name: string): string =>
    [
        `if SHIELD_${s.left.toUpperCase()}`,
        ``,
        `config ZMK_KEYBOARD_NAME`,
        `\tdefault "${dtsString(name.slice(0, 16))}"`,
        ``,
        `config ZMK_SPLIT_ROLE_CENTRAL`,
        `\tdefault y`,
        ``,
        `endif # SHIELD_${s.left.toUpperCase()}`,
        ``,
        `if SHIELD_${s.left.toUpperCase()} || SHIELD_${s.right.toUpperCase()}`,
        ``,
        `config ZMK_SPLIT`,
        `\tdefault y`,
        ``,
        `endif`,
        ``,
    ].join('\n')

// A ZMK split board ships ONE shield dir with a shared keymap/conf/dtsi base and
// two half overlays; build.yaml builds both halves on the same board.
function zmkSplitBundle(
    config: ConfigKeymap,
    split: ZmkSplitShields,
): ProjectBundle {
    const ctrl = resolveController(config)
    const board = ctrl.board || 'YOUR_BOARD'
    const { files: compiled, diagnostics } = getCompiler('zmk').compile(config)
    const keymap = compiled.find((f) => f.filename.endsWith('.keymap'))
    const dtsi = compiled.find((f) => f.filename.endsWith('.dtsi'))
    const leftOv = compiled.find((f) => f.filename.endsWith('_left.overlay'))
    const rightOv = compiled.find((f) => f.filename.endsWith('_right.overlay'))

    const shieldDir = `config/boards/shields/${split.base}`
    const buildYaml = [
        `include:`,
        `  - board: ${board}`,
        `    shield: ${split.left}`,
        `  - board: ${board}`,
        `    shield: ${split.right}`,
        ``,
    ].join('\n')

    const readme = [
        `# ${config.meta.name} — ZMK config (split)`,
        ``,
        `Generated by remappr. Ready-to-build \`zmk-config\` for a SPLIT keyboard,`,
        `with one shield dir \`${shieldDir}/\` holding both halves.`,
        ``,
        `## Build in the cloud (no toolchain)`,
        `1. Create a new GitHub repository and push these files.`,
        `2. The workflow builds BOTH halves (\`${split.left}\` + \`${split.right}\`).`,
        `3. Flash \`${split.left}\` to one half and \`${split.right}\` to the other.`,
        ``,
        `## Build locally`,
        `\`\`\`sh`,
        `west init -l config && west update`,
        `west build -s zmk/app -b ${board} -- -DSHIELD=${split.left} -DZMK_CONFIG="$(pwd)/config"`,
        `west build -s zmk/app -b ${board} -- -DSHIELD=${split.right} -DZMK_CONFIG="$(pwd)/config"`,
        `\`\`\``,
        ``,
        `## Notes`,
        `- \`${split.base}.dtsi\` is the shared base (physical layout, matrix-transform,`,
        `  rows-only kscan, chosen). \`${split.left}.overlay\` / \`${split.right}.overlay\``,
        `  set each half's col-gpios; the right half offsets the transform.`,
        `- Both halves share \`${split.base}.keymap\` and \`${split.base}.conf\`.`,
        `- Re-check the per-half col-gpios + the matrix-transform \`RC()\` map against`,
        `  your real wiring — remappr derives them from physical key position.`,
        ``,
    ].join('\n')

    const files: ExportedFile[] = [
        text(
            `${shieldDir}/${split.base}.keymap`,
            keymap ? asText(keymap.content) : '',
        ),
        text(`${shieldDir}/${split.base}.conf`, deriveZmkConf(config)),
        text(`${shieldDir}/Kconfig.shield`, kconfigShieldSplit(split)),
        text(
            `${shieldDir}/Kconfig.defconfig`,
            kconfigDefconfigSplit(split, config.meta.name),
        ),
        text(
            `${shieldDir}/${split.base}.zmk.yml`,
            shieldMetaYml(split.base, config.meta.name),
        ),
    ]
    if (dtsi)
        files.push(
            text(`${shieldDir}/${split.base}.dtsi`, asText(dtsi.content)),
        )
    if (leftOv)
        files.push(
            text(`${shieldDir}/${split.left}.overlay`, asText(leftOv.content)),
        )
    if (rightOv)
        files.push(
            text(
                `${shieldDir}/${split.right}.overlay`,
                asText(rightOv.content),
            ),
        )
    files.push(
        text(`config/west.yml`, ZMK_WEST_YML),
        text(`build.yaml`, buildYaml),
        text(`.github/workflows/build.yml`, ZMK_BUILD_WORKFLOW),
        text(`README.md`, readme),
    )

    return { files, diagnostics, rootName: `${split.base}-zmk-config` }
}

/* ── QMK ─────────────────────────────────────────────────────────────────── */

const QMK_BUILD_WORKFLOW = [
    `name: Build QMK firmware`,
    `on: [push, pull_request, workflow_dispatch]`,
    `jobs:`,
    `  build:`,
    `    uses: qmk/.github/workflows/qmk_userspace_build.yml@main`,
    `    with:`,
    `      qmk_repo: qmk/qmk_firmware`,
    `      qmk_ref: master`,
    ``,
].join('\n')

function qmkBundle(config: ConfigKeymap, target: Target): ProjectBundle {
    const kb = sanitize(config.keyboard.id || config.meta.name)
    const km = 'remappr'
    const { files: compiled, diagnostics } = getCompiler(target).compile(config)
    const keymapC = compiled.find((f) => f.filename.endsWith('.c'))
    const kbDir = `keyboards/${kb}`
    const base = `${kbDir}/keymaps/${km}`
    const { json: keyboardJson, diagnostics: kbDiag } =
        buildQmkKeyboardJson(config)

    // VIA / Vial both build through the QMK family and need VIA support compiled
    // in; when targeted, enable VIA in the keymap and ship the VIA definition the
    // app loads in its Authoring/Design tab (the matrix-annotated KLE keymap).
    const wantsVia = (config.keyboard.firmware ?? []).some(
        (f) => f === 'via' || f === 'vial',
    )
    const { json: viaJson, diagnostics: viaDiag } = wantsVia
        ? buildViaJson(config)
        : { json: null, diagnostics: [] as Diagnostic[] }

    // Vial layers its security (UID + unlock combo) on top of VIA: it ships its own
    // matrix-annotated `vial.json` in the keymap and adds VIAL_ENABLE + a config.h.
    const wantsVial = (config.keyboard.firmware ?? []).includes('vial')
    const vial = wantsVial
        ? buildVialJson(config)
        : { json: null, configH: '', diagnostics: [] as Diagnostic[] }

    const rulesMk = deriveQmkRulesMk(config, wantsVia, wantsVial)
    // Vial's UID/unlock defines go in the keymap config.h alongside board overrides.
    const configH = wantsVial
        ? deriveQmkConfigH(config) + '\n' + vial.configH
        : deriveQmkConfigH(config)

    const qmkJson = JSON.stringify(
        { userspace_version: '1.1', build_targets: [[kb, km]] },
        null,
        2,
    )

    const readme = [
        `# ${config.meta.name} — QMK keyboard + userspace`,
        ``,
        `Generated by remappr as a \`qmk_userspace\` tree with a complete`,
        `keyboard definition (\`${kbDir}/keyboard.json\`).`,
        ``,
        `## Build in the cloud`,
        `1. Push these files to a GitHub repo (a fork of \`qmk/qmk_userspace\` works).`,
        `2. The included workflow builds the keymap on every push.`,
        `3. Download the firmware artifact from the Actions run.`,
        ``,
        `## Build locally`,
        `\`\`\`sh`,
        `qmk userspace-compile`,
        `# or: qmk compile -kb ${kb} -km ${km}`,
        `\`\`\``,
        ``,
        `## Notes`,
        `- \`${kbDir}/keyboard.json\` is the data-driven keyboard definition`,
        `  (matrix pins, diode direction, MCU/USB identity, features, layout).`,
        `- Verify the pin names + processor/bootloader against your hardware before`,
        `  flashing — remappr fills them from the builder's Controller panel.`,
        ...(wantsVia
            ? [
                  ``,
                  `## VIA`,
                  `- \`VIA_ENABLE = yes\` is set in \`${base}/rules.mk\`, so the built`,
                  `  firmware supports VIA / Vial.`,
                  `- \`via/${kb}.json\` is the VIA keyboard definition — load it in the`,
                  `  VIA app's Authoring/Design tab (the \`vendorId\`/\`productId\` must`,
                  `  match the firmware).`,
              ]
            : []),
        ...(wantsVial
            ? [
                  ``,
                  `## Vial`,
                  `- \`VIAL_ENABLE = yes\` is set in \`${base}/rules.mk\` and`,
                  `  \`${base}/vial.json\` is the Vial definition the firmware embeds.`,
                  `- \`${base}/config.h\` carries \`VIAL_KEYBOARD_UID\` + the unlock combo.`,
                  `  Generate a unique UID and pick unlock keys in the builder before`,
                  `  shipping (a placeholder/insecure build still compiles).`,
              ]
            : []),
        ``,
    ].join('\n')

    const files: ExportedFile[] = [
        text(
            `${kbDir}/keyboard.json`,
            JSON.stringify(keyboardJson, null, 4) + '\n',
        ),
        text(`${base}/keymap.c`, keymapC ? asText(keymapC.content) : ''),
        text(`${base}/rules.mk`, rulesMk),
        text(`${base}/config.h`, configH),
        text(`qmk.json`, qmkJson + '\n'),
        text(`.github/workflows/build_binaries.yml`, QMK_BUILD_WORKFLOW),
        text(`README.md`, readme),
    ]
    if (viaJson)
        files.push(
            text(`via/${kb}.json`, JSON.stringify(viaJson, null, 4) + '\n'),
        )
    if (vial.json)
        files.push(
            text(
                `${base}/vial.json`,
                JSON.stringify(vial.json, null, 4) + '\n',
            ),
        )

    return {
        files,
        diagnostics: [
            ...diagnostics,
            ...kbDiag,
            ...viaDiag,
            ...vial.diagnostics,
        ],
        rootName: `${kb}-qmk-userspace`,
    }
}

/** Build the full project bundle for a target. ZMK → zmk-config skeleton;
 *  QMK/Keychron → qmk_userspace skeleton. */
export function buildProjectBundle(
    config: ConfigKeymap,
    target: Target,
): ProjectBundle {
    return target === 'zmk' ? zmkBundle(config) : qmkBundle(config, target)
}
