// pattern-check: skip pure string-template derivation, no abstraction
//
// Single source of truth for the firmware CONFIG files: the ZMK `.conf` (Kconfig)
// and the QMK-family `config.h` / `rules.mk`. Both the project-bundle emitter
// (bundle.ts) and the builder's live preview (BuilderMetaForm) call these so the
// file the user sees in the UI is byte-identical to what ships in the archive.
//
// Flags are TRI-STATE: `firmwareConfig.<x>` undefined ⇒ auto-derive from the used
// behaviors + declared hardware; explicit true/false ⇒ user override. `someAction`
// (the behavior walker) lives here so bundle.ts can import it back without a cycle.

import type { CanonAction, ConfigKeymap } from './types'

/** Walk every action in the config (layers, encoders, combos) for feature flags. */
export function someAction(
    config: ConfigKeymap,
    pred: (a: CanonAction) => boolean,
): boolean {
    for (const layer of config.layers) {
        if (layer.bindings.some(pred)) return true
        for (const e of layer.encoders ?? []) {
            if (pred(e.cw) || pred(e.ccw) || (e.press && pred(e.press)))
                return true
        }
        for (const eb of Object.values(layer.encoderBindings ?? {})) {
            if (pred(eb.cw) || pred(eb.ccw) || (eb.press && pred(eb.press)))
                return true
        }
    }
    return (config.combos ?? []).some((c) => pred(c.action))
}

const isMouse = (a: CanonAction): boolean =>
    a.type === 'mouse_key' ||
    a.type === 'mouse_move' ||
    a.type === 'mouse_scroll'

/** The resolved (override ?? auto-derived) ZMK feature set — also drives the UI. */
export interface ZmkConfFlags {
    usb: boolean
    ble: boolean
    studio: boolean
    studioLocking: boolean
    studioCdc: boolean
    softOff: boolean
    extPower: boolean
    pointing: boolean
    backlight: boolean
    underglow: boolean
    usbLogging: boolean
}

/** Resolve every ZMK flag from `firmwareConfig` overrides + used behaviors/hardware. */
export function resolveZmkConfFlags(config: ConfigKeymap): ZmkConfFlags {
    const fc = config.keyboard.firmwareConfig ?? {}
    const hw = config.keyboard.hardware
    const uses = (p: (a: CanonAction) => boolean): boolean =>
        someAction(config, p)

    // Underglow/backlight are owned by the builder's Lighting section
    // (keyboard.lighting); enabling lighting there drives the .conf flag, on top
    // of any lighting *behavior* in the keymap or declared peripheral hardware.
    const lighting = config.keyboard.lighting
    const usesUnderglow =
        !!lighting?.underglow ||
        uses((a) => a.type === 'lighting' && a.target === 'underglow')
    const usesBacklight =
        !!lighting?.backlight ||
        uses((a) => a.type === 'lighting' && a.target === 'backlight')
    const studio = fc.studio ?? true
    return {
        usb: fc.usb ?? true,
        ble: fc.ble ?? false,
        studio,
        studioLocking: fc.studioLocking ?? true,
        studioCdc: fc.studioUsbCdc ?? studio,
        softOff: fc.softOff ?? uses((a) => a.type === 'soft_off'),
        extPower:
            fc.extPower ??
            (uses((a) => a.type === 'ext_power') || !!hw?.extPowerCtrl),
        pointing: fc.pointing ?? uses(isMouse),
        backlight: fc.backlight ?? (usesBacklight || !!hw?.backlightPwm),
        underglow: fc.underglow ?? (usesUnderglow || !!hw?.ws2812),
        usbLogging: fc.usbLogging ?? false,
    }
}

/** Comment a flag line out when its feature is off (Kconfig hint convention). */
const flag = (on: boolean, line: string): string => (on ? line : `# ${line}`)

/** The complete ZMK `.conf` (Kconfig) for the config — overrides + auto-derived. */
export function deriveZmkConf(config: ConfigKeymap): string {
    const fc = config.keyboard.firmwareConfig ?? {}
    const on = resolveZmkConfFlags(config)
    const lines: string[] = [
        `# ZMK config for ${config.meta.name}`,
        `# Generated by remappr — toggles derive from your behaviors + hardware.`,
        ``,
        `# ── Transports ──`,
        flag(on.usb, `CONFIG_ZMK_USB=y`),
        flag(on.ble, `CONFIG_ZMK_BLE=y`),
        ``,
    ]

    if (on.pointing)
        lines.push(
            `# Pointing (&mkp / &mmv / &msc).`,
            `CONFIG_ZMK_POINTING=y`,
            ``,
        )

    if (on.studio) {
        lines.push(`# ── ZMK Studio ──`, `CONFIG_ZMK_STUDIO=y`)
        if (on.studioCdc)
            lines.push(
                `# Studio over USB needs a CDC ACM endpoint (studio_acm in the overlay).`,
                `CONFIG_SERIAL=y`,
                `CONFIG_USB_DEVICE_STACK=y`,
                `CONFIG_USB_CDC_ACM=y`,
                `CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y`,
                `CONFIG_ZMK_STUDIO_TRANSPORT_UART=y`,
            )
        // Locking is on by default; an explicit `=n` (not a comment) disables it.
        lines.push(
            on.studioLocking
                ? `CONFIG_ZMK_STUDIO_LOCKING=y`
                : `CONFIG_ZMK_STUDIO_LOCKING=n`,
        )
        lines.push(``)
    }

    if (on.softOff)
        lines.push(`# Soft-off (&soft_off).`, `CONFIG_ZMK_PM_SOFT_OFF=y`, ``)

    if (on.backlight)
        lines.push(
            `# Backlight (&bl) via PWM.`,
            `CONFIG_ZMK_BACKLIGHT=y`,
            `CONFIG_PWM=y`,
            ``,
        )
    else lines.push(`# CONFIG_ZMK_BACKLIGHT=y`)

    lines.push(flag(on.underglow, `CONFIG_ZMK_RGB_UNDERGLOW=y`))

    if (on.extPower)
        lines.push(`# Ext-power (&ext_power).`, `CONFIG_ZMK_EXT_POWER=y`)

    lines.push(
        ``,
        `# ── Optional ──`,
        flag(on.usbLogging, `CONFIG_ZMK_USB_LOGGING=y`),
    )

    if (fc.kconfig?.trim())
        lines.push(
            ``,
            `# ── Extra Kconfig (from builder) ──`,
            fc.kconfig.trim(),
        )

    return lines.join('\n') + '\n'
}

/** The QMK keymap `config.h` (pragma block + user `firmwareConfig.configH` extras).
 *  Vial's UID/unlock defines are concatenated by the caller (they come from the
 *  vial build result, not the config). */
export function deriveQmkConfigH(config: ConfigKeymap): string {
    const fc = config.keyboard.firmwareConfig ?? {}
    const lines = [
        `#pragma once`,
        `// remappr — board-level overrides go here.`,
        `// Matrix pins, diode direction, processor/bootloader and USB identity`,
        `// are data-driven in keyboard.json; add only extras config.h must`,
        `// carry (e.g. #define WS2812_SPI_DRIVER SPID2).`,
    ]
    if (fc.configH?.trim())
        lines.push(``, `// ── Extra (from builder) ──`, fc.configH.trim())
    return lines.join('\n') + '\n'
}

/** The QMK keymap `rules.mk`: VIA/Vial feature toggles + user `rulesMk` extras. */
export function deriveQmkRulesMk(
    config: ConfigKeymap,
    wantsVia: boolean,
    wantsVial: boolean,
): string {
    const fc = config.keyboard.firmwareConfig ?? {}
    let out =
        `# remappr keymap — feature toggles live in keyboard.json\n` +
        (wantsVia ? `VIA_ENABLE = yes\n` : ``) +
        (wantsVial ? `VIAL_ENABLE = yes\n` : ``)
    if (fc.rulesMk?.trim())
        out += `# Extra (from builder)\n${fc.rulesMk.trim()}\n`
    return out
}
