// pattern-check: skip — board-hardware devicetree string emitters, no abstraction
//
// Board-hardware devicetree nodes that remappr CAN derive from the builder's
// hardware fields: kscan (explicit or synthesized from pin labels), chosen,
// ext-power, backlight PWM, WS2812 underglow (with SoC-aware pinctrl), the studio
// CDC endpoint, plus the NOT-GENERATED checklist for what stays board-specific.

import type { DiagnosticBag } from '../../diagnostics'
import { gpioSpec, type PinRole, resolveZmkPin } from '../../pinmaps'
import { resolveController } from '../../controller'
import type {
    CanonBacklightPwm,
    CanonExtPowerCtrl,
    CanonKscan,
    CanonWs2812,
    ConfigHardware,
    ConfigKeymap,
    DiodeDirection,
} from '../../types'

// Board-hardware nodes remappr cannot derive — the ZMK connection never exposes
// them. Emitted as a checklist comment so the file is a clear skeleton. When the
// builder supplies a kscan, the kscan/chosen/matrix-transform lines are GENERATED
// (see emitKscan/emitChosen) and drop out of this list, leaving only the
// SoC/peripheral nodes that still must come from the board's own overlay.
export function notGeneratedBlock(
    hasKscan: boolean,
    hw: ConfigHardware | undefined,
): string[] {
    // Peripherals remappr now emits drop out of the checklist.
    const hasLighting = !!(hw?.backlightPwm || hw?.ws2812)
    const hasExtPower = !!hw?.extPowerCtrl
    const hasAnyPeripheral = hasLighting || hasExtPower
    const items = [
        ...(hasKscan
            ? []
            : [
                  ` *   • kscan          — matrix/direct GPIO scan + row/col gpios`,
                  ` *   • chosen         — zmk,kscan / zmk,physical-layout / zmk,matrix-transform`,
                  ` *   • &gpio / diode-direction, debounce timings`,
              ]),
        // pinctrl for the kscan GPIOs is still board-specific; pinctrl for the
        // generated PWM/SPI peripherals IS emitted, so only mention kscan pins.
        ` *   • pinctrl / pins — SoC pin mux for the kscan GPIOs`,
        ...(hasLighting
            ? []
            : [
                  ` *   • underglow / backlight / RGB LED drivers (e.g. &led_strip)`,
              ]),
        ` *   • encoders (EC11 sensors) + sensor-channel wiring`,
        ...(hasExtPower
            ? []
            : [` *   • power / battery / ext-power control nodes`]),
        ` *   • display, pointing device, or other peripheral nodes`,
    ]
    const tail = hasKscan
        ? []
        : [
              ` *`,
              ` * Also re-check the matrix-transform RC() map above against your real`,
              ` * kscan — it is derived from physical position, not electrical wiring.`,
          ]
    const note = hasAnyPeripheral
        ? [
              ` *`,
              ` * Verify the generated peripheral pins (PWM/SPI/ext-power) against your`,
              ` * board's real wiring — remappr fills them from the builder's pin fields.`,
          ]
        : []
    return [
        `/* ─────────────────────────────────────────────────────────────────────`,
        ` * NOT GENERATED by remappr — board-specific hardware, add from your`,
        ` * board/shield overlay (these are wiring, not keymap):`,
        ` *`,
        ...items,
        ...tail,
        ...note,
        ` * ───────────────────────────────────────────────────────────────────── */`,
    ]
}

// Format a devicetree GPIO-list property: `name = <spec> , <spec> ;` one per
// line, mirroring a hand-written kscan node. Each spec is the user's verbatim
// phandle+flags string (e.g. "&gpio0 4 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)").
function gpioListProp(name: string, specs: string[]): string[] {
    return [
        `        ${name}`,
        ...specs.map((s, i) => `            ${i === 0 ? '=' : ','} <${s}>`),
        `            ;`,
    ]
}

// Emit a `zmk,kscan-gpio-{matrix,direct}` node, labelled `kscan0` so `chosen`
// can point `zmk,kscan` at it.
export function emitKscan(kscan: CanonKscan): string[] {
    const out = [`    kscan0: kscan {`]
    if (kscan.type === 'matrix') {
        out.push(`        compatible = "zmk,kscan-gpio-matrix";`)
        out.push(`        diode-direction = "${kscan.diodeDirection}";`)
        out.push(...gpioListProp('row-gpios', kscan.rowGpios))
        out.push(...gpioListProp('col-gpios', kscan.colGpios))
    } else {
        out.push(`        compatible = "zmk,kscan-gpio-direct";`)
        out.push(...gpioListProp('input-gpios', kscan.inputGpios))
    }
    if (kscan.debouncePressMs !== undefined)
        out.push(`        debounce-press-ms = <${kscan.debouncePressMs}>;`)
    if (kscan.debounceReleaseMs !== undefined)
        out.push(`        debounce-release-ms = <${kscan.debounceReleaseMs}>;`)
    out.push(`    };`)
    return out
}

// Emit a devicetree GPIO-list property, resolving each FRIENDLY pin label via the
// board pin map. Resolved labels become a real `<&phandle pin FLAGS>` spec;
// unresolved ones (unknown board/label, or a missing per-key pin) become a TODO
// comment line + a `warn`, so the build clearly flags what the user must fill.
export function resolvedGpioListProp(
    name: string,
    labels: string[],
    board: string | undefined,
    role: PinRole,
    diag: DiagnosticBag,
): string[] {
    const lines = [`        ${name}`]
    let firstReal = true
    labels.forEach((label, i) => {
        const trimmed = label.trim()
        const core = trimmed ? resolveZmkPin(board, trimmed) : null
        if (core) {
            lines.push(
                `            ${firstReal ? '=' : ','} <${gpioSpec(core, role)}>`,
            )
            firstReal = false
        } else if (!trimmed) {
            diag.warn(
                `${name}: position ${i} has no pin assigned — add the GpioSpec manually`,
                ['keyboard', 'pins'],
            )
            lines.push(
                `            /* [${i}] no pin assigned — add ${firstReal ? '=' : ','} <&gpio0 N FLAGS> */`,
            )
        } else {
            diag.warn(
                `pin "${trimmed}" not resolvable for board ${board ?? '(unset)'} — fill the ${name} GpioSpec manually`,
                ['keyboard', 'pins'],
            )
            lines.push(
                `            /* "${trimmed}" — no GpioSpec for board ${board ?? '(unset)'}; add ${firstReal ? '=' : ','} <&gpio0 N FLAGS> */`,
            )
        }
    })
    lines.push(`            ;`)
    return lines
}

// Synthesize a `kscan0` node from the builder's FRIENDLY pin labels when no
// explicit `hardware.kscan` was supplied: `keyboard.pins` (row/col labels) →
// matrix, else per-key `pin` → direct. Returns null when there are no pins to
// work with (caller then emits the geometry-only scaffold). `pins` carries no
// diode direction, so a matrix assumes the ZMK-common `col2row`.
export function emitSynthKscan(
    config: ConfigKeymap,
    diag: DiagnosticBag,
): string[] | null {
    const board = resolveController(config).board
    const pins = config.keyboard.pins
    if (pins && pins.rows.length && pins.cols.length) {
        const dir: DiodeDirection = 'col2row'
        const rowRole: PinRole = dir === 'col2row' ? 'input' : 'output'
        const colRole: PinRole = dir === 'col2row' ? 'output' : 'input'
        return [
            `    kscan0: kscan {`,
            `        compatible = "zmk,kscan-gpio-matrix";`,
            `        /* diode-direction assumed "${dir}" — remappr pin labels carry none; verify. */`,
            `        diode-direction = "${dir}";`,
            ...resolvedGpioListProp(
                'row-gpios',
                pins.rows,
                board,
                rowRole,
                diag,
            ),
            ...resolvedGpioListProp(
                'col-gpios',
                pins.cols,
                board,
                colRole,
                diag,
            ),
            `    };`,
        ]
    }
    const keyPins = config.keyboard.keys.map((k) => k.pin ?? '')
    if (keyPins.some((p) => p.trim())) {
        return [
            `    kscan0: kscan {`,
            `        compatible = "zmk,kscan-gpio-direct";`,
            ...resolvedGpioListProp(
                'input-gpios',
                keyPins,
                board,
                'direct',
                diag,
            ),
            `    };`,
        ]
    }
    return null
}

// `chosen` node wiring the generated kscan + physical-layout + any generated
// peripheral nodes (backlight / underglow / ext-power / studio CDC). The transform
// is referenced by the physical-layout's own `transform` property, so it is not
// repeated here. Returns [] when there is nothing to choose.
export function emitChosen(
    hasKscan: boolean,
    hw: ConfigHardware | undefined,
): string[] {
    const entries = [
        ...(hasKscan ? [`        zmk,kscan = <&kscan0>;`] : []),
        ...(hasKscan
            ? [`        zmk,physical-layout = <&physical_layout_default>;`]
            : []),
        ...(hw?.backlightPwm
            ? [`        zmk,backlight = <&backlight_pwm>;`]
            : []),
        ...(hw?.ws2812 ? [`        zmk,underglow = <&led_strip>;`] : []),
        ...(hw?.extPowerCtrl
            ? [`        zmk,ext-power = <&ext_power_ctrl>;`]
            : []),
        ...(hw?.studioAcm
            ? [`        zmk,studio-rpc-uart = <&studio_acm>;`]
            : []),
    ]
    return entries.length ? [`    chosen {`, ...entries, `    };`] : []
}

// ── full-parity peripheral overlay nodes ────────────────────────────────────
// Parse an nRF pin label "P0.13" → {port:0, pin:13}; null if not that form.
function parseNrfPin(s: string): { port: number; pin: number } | null {
    const m = /^P(\d+)\.(\d+)$/i.exec(s.trim())
    return m ? { port: Number(m[1]), pin: Number(m[2]) } : null
}

// Which ZMK SoC family a controller board belongs to. Pin-mux (pinctrl) syntax is
// SoC-specific — only nRF gets full NRF_PSEL generation; others get a labelled
// FIXME scaffold the user completes with their board's pinctrl bindings.
type ZmkSoc = 'nrf' | 'rp2040' | 'unknown'
function boardSoc(board: string | undefined): ZmkSoc {
    const b = (board ?? '').toLowerCase()
    if (!b) return 'unknown'
    if (b.includes('nrf') || b.includes('nice_nano') || b.includes('xiao_ble'))
        return 'nrf'
    if (b.includes('rp2040') || b.includes('pico')) return 'rp2040'
    return 'unknown'
}

// A default+sleep pinctrl group pair for an nRF instance, both pointing at the
// same psel (sleep adds low-power-enable). Shared by the PWM + SPI emitters.
function nrfPinctrlPair(instance: string, psel: string): string[] {
    return [
        `    ${instance}_default: ${instance}_default {`,
        `        group1 {`,
        `            psels = <${psel}>;`,
        `        };`,
        `    };`,
        `    ${instance}_sleep: ${instance}_sleep {`,
        `        group1 {`,
        `            psels = <${psel}>;`,
        `            low-power-enable;`,
        `        };`,
        `    };`,
    ]
}

// A clearly-FIXME pinctrl scaffold for non-nRF SoCs: the default+sleep groups
// exist (so the &instance block's pinctrl-0/-1 refs resolve) but the pin-mux is
// a placeholder the user must replace with their board's binding. nRF uses
// `psels = <NRF_PSEL(...)>`; RP2040 uses `pinmux = <…>` from the rpi-pico header.
function fixmePinctrlPair(
    instance: string,
    soc: ZmkSoc,
    pin: string,
    fn: string,
): string[] {
    const hint =
        soc === 'rp2040'
            ? 'RP2040: pinmux = <…> from <zephyr/dt-bindings/pinctrl/rpi-pico-rp2040-pinctrl.h>'
            : 'set your SoC pin-mux (nRF: psels=<NRF_PSEL(…)>; RP2040: pinmux=<…>)'
    const group = (extra: string[]): string[] => [
        `        /* FIXME (${soc}): pin-mux for ${fn} pin "${pin}" — ${hint}. */`,
        `        group1 {`,
        `            psels = <0>;`,
        ...extra,
        `        };`,
    ]
    return [
        `    ${instance}_default: ${instance}_default {`,
        ...group([]),
        `    };`,
        `    ${instance}_sleep: ${instance}_sleep {`,
        ...group([`            low-power-enable;`]),
        `    };`,
    ]
}

// Resolve a single control/data pin label → a devicetree GPIO core "&gpioN M".
// Accepts "P0.13", a verbatim "&gpio0 13 ..." (passed through), else null.
function gpioCoreFromPin(s: string): string | null {
    const t = s.trim()
    if (!t) return null
    if (t.startsWith('&')) return t
    const p = parseNrfPin(t)
    return p ? `&gpio${p.port} ${p.pin}` : null
}

// Devicetree `color-mapping` value for a WS2812 wire order.
function colorMapping(order: NonNullable<CanonWs2812['colorOrder']>): string {
    const ID: Record<string, string> = {
        R: 'LED_COLOR_ID_RED',
        G: 'LED_COLOR_ID_GREEN',
        B: 'LED_COLOR_ID_BLUE',
        W: 'LED_COLOR_ID_WHITE',
    }
    return order
        .split('')
        .map((c) => ID[c])
        .join(' ')
}

// `zmk,ext-power-generic` control node (lives inside `/ {}`).
export function emitExtPowerGeneric(
    ep: CanonExtPowerCtrl,
    diag: DiagnosticBag,
): string[] {
    const flags = ep.activeLow ? 'GPIO_ACTIVE_LOW' : 'GPIO_ACTIVE_HIGH'
    const core = gpioCoreFromPin(ep.controlGpio)
    if (!core)
        diag.warn(
            `ext-power control-gpios "${ep.controlGpio}" not parseable — set the GPIO manually`,
            ['keyboard', 'hardware', 'extPowerCtrl'],
        )
    const spec = core
        ? `${core} ${flags}`
        : `&gpio0 0 ${flags} /* FIXME: "${ep.controlGpio}" */`
    return [
        `    ext_power_ctrl: ext_power_ctrl {`,
        `        compatible = "zmk,ext-power-generic";`,
        `        control-gpios = <${spec}>;`,
        ...(ep.initDelayMs !== undefined
            ? [`        init-delay-ms = <${ep.initDelayMs}>;`]
            : []),
        `    };`,
    ]
}

// Backlight: the `pwm-leds` root node + the `&pwm<n>` override + a `&pinctrl`
// group pair. nRF "P<port>.<pin>" pins get a real NRF_PSEL; other SoCs get a
// labelled FIXME pinctrl scaffold (the block is always emitted so the structure
// is complete — the user fills the board-specific pin-mux).
export function emitBacklightPwm(
    bl: CanonBacklightPwm,
    diag: DiagnosticBag,
    board: string | undefined,
): { root: string[]; pinctrl: string[]; block: string[] } {
    const period = bl.periodMs ?? 10
    const polarity = bl.inverted
        ? 'PWM_POLARITY_INVERTED'
        : 'PWM_POLARITY_NORMAL'
    const root = [
        `    backlight_pwm: backlight_pwm {`,
        `        compatible = "pwm-leds";`,
        `        bl_led_0: bl_led_0 {`,
        `            pwms = <&${bl.instance} ${bl.channel} PWM_MSEC(${period}) ${polarity}>;`,
        `        };`,
        `    };`,
    ]
    const block = [
        `&${bl.instance} {`,
        `    status = "okay";`,
        `    pinctrl-0 = <&${bl.instance}_default>;`,
        `    pinctrl-1 = <&${bl.instance}_sleep>;`,
        `    pinctrl-names = "default", "sleep";`,
        `};`,
    ]
    const soc = boardSoc(board)
    const p = parseNrfPin(bl.pin)
    if (soc === 'nrf' && p) {
        const psel = `NRF_PSEL(PWM_OUT${bl.channel}, ${p.port}, ${p.pin})`
        return { root, pinctrl: nrfPinctrlPair(bl.instance, psel), block }
    }
    diag.warn(
        `backlight pin "${bl.pin}" on a ${soc} board — pinctrl emitted as a FIXME scaffold; complete the &${bl.instance} pin-mux for your board`,
        ['keyboard', 'hardware', 'backlightPwm'],
    )
    return {
        root,
        pinctrl: fixmePinctrlPair(bl.instance, soc, bl.pin, 'PWM backlight'),
        block,
    }
}

// Underglow: the `&spi<n>` block with a `worldsemi,ws2812-spi` led_strip child +
// a `&pinctrl` MOSI group pair. The SPI controller `compatible` + pin-mux are
// SoC-specific: nRF emits `nordic,nrf-spim` + a real NRF_PSEL; other SoCs emit
// the matching `compatible` (best-effort) + a FIXME pinctrl scaffold to complete.
export function emitWs2812(
    ws: CanonWs2812,
    diag: DiagnosticBag,
    board: string | undefined,
): { pinctrl: string[]; block: string[] } {
    const freq = ws.spiMaxFrequency ?? 4000000
    const mapping = colorMapping(ws.colorOrder ?? 'GRB')
    const soc = boardSoc(board)
    const spiCompatible =
        soc === 'rp2040' ? 'raspberrypi,pico-spi' : 'nordic,nrf-spim'
    const block = [
        `&${ws.spi} {`,
        ...(soc === 'nrf'
            ? []
            : [
                  `    /* FIXME (${soc}): verify the SPI controller compatible + that ws2812-over-SPI`,
                  `       suits this SoC (RP2040 underglow is often PIO-based, not SPI). */`,
              ]),
        `    compatible = "${spiCompatible}";`,
        `    status = "okay";`,
        `    pinctrl-0 = <&${ws.spi}_default>;`,
        `    pinctrl-1 = <&${ws.spi}_sleep>;`,
        `    pinctrl-names = "default", "sleep";`,
        ``,
        `    led_strip: ws2812@0 {`,
        `        compatible = "worldsemi,ws2812-spi";`,
        `        reg = <0>;`,
        `        spi-max-frequency = <${freq}>;`,
        `        chain-length = <${ws.chainLength}>;`,
        `        spi-one-frame = <0x70>;`,
        `        spi-zero-frame = <0x40>;`,
        `        color-mapping = <${mapping}>;`,
        `    };`,
        `};`,
    ]
    const p = parseNrfPin(ws.dataPin)
    if (soc === 'nrf' && p) {
        const psel = `NRF_PSEL(SPIM_MOSI, ${p.port}, ${p.pin})`
        return { pinctrl: nrfPinctrlPair(ws.spi, psel), block }
    }
    diag.warn(
        `WS2812 data pin "${ws.dataPin}" on a ${soc} board — pinctrl emitted as a FIXME scaffold; complete the &${ws.spi} pin-mux (and verify ws2812-over-SPI fits this SoC)`,
        ['keyboard', 'hardware', 'ws2812'],
    )
    return {
        pinctrl: fixmePinctrlPair(ws.spi, soc, ws.dataPin, 'WS2812 SPI MOSI'),
        block,
    }
}

// CDC-ACM endpoint for ZMK Studio's RPC-over-USB transport.
export function emitStudioAcm(): string[] {
    return [
        `&zephyr_udc0 {`,
        `    studio_acm: studio_acm {`,
        `        compatible = "zephyr,cdc-acm-uart";`,
        `    };`,
        `};`,
    ]
}
