// Pattern check: Strategy (Tier 1) — extended — concrete ZMK KeymapCompiler
// registered into the Strategy registry in compiler.ts.
//
// Assembles the ZMK `.keymap` devicetree from the canonical config (behaviors,
// macros, tap-dances, encoders, combos, conditional layers, the layer keymap) and
// pairs it with the `.overlay` (or split `.dtsi`+overlays). Behavior coverage
// tracks https://zmk.dev/docs/keymaps/behaviors. The per-binding lowering lives in
// bindings.ts; node emitters in behaviors.ts / hardware.ts / overlay.ts.

import type { ExportedFile } from '../../../types'
import type { DiagnosticBag } from '../../diagnostics'
import {
    runCompile,
    registerCompiler,
    type KeymapCompiler,
} from '../../compiler'
import type { ConfigKeymap } from '../../types'
import { type Ctx, emitBinding } from './bindings'
import {
    emitEncoderSensors,
    emitHoldTapDefs,
    emitMacros,
    emitModMorphs,
    emitSliderInputs,
    emitTapDances,
} from './behaviors'
import { emitOverlay, emitSplitOverlay } from './overlay'
import { dtsString, sanitize } from './maps'

function emitKeymap(config: ConfigKeymap, diag: DiagnosticBag): ExportedFile[] {
    const ctx: Ctx = {
        layerIndex: new Map(config.layers.map((l, i) => [l.name, i])),
        diag,
        genHoldTaps: new Map(),
    }

    const lines: string[] = []
    lines.push(
        `/* Generated by remappr — ZMK keymap for ${config.keyboard.name}.`,
        ` * Keymap layers, behaviors, combos, macros and tap-dances only.`,
        ` * Physical layout + matrix-transform live in the .overlay; board`,
        ` * hardware (kscan, pinctrl, LED drivers, …) is NOT generated — see`,
        ` * the "NOT GENERATED" checklist in the .overlay. */`,
    )
    lines.push(`#include <behaviors.dtsi>`)
    lines.push(`#include <dt-bindings/zmk/keys.h>`)
    lines.push(`#include <dt-bindings/zmk/bt.h>`)
    lines.push(`#include <dt-bindings/zmk/outputs.h>`)
    lines.push(`#include <dt-bindings/zmk/rgb.h>`)
    lines.push(`#include <dt-bindings/zmk/backlight.h>`)
    lines.push(`#include <dt-bindings/zmk/ext_power.h>`)
    lines.push(`#include <dt-bindings/zmk/pointing.h>`)
    lines.push(``)
    lines.push(`/ {`)

    if (config.macros?.length) lines.push(...emitMacros(config.macros, ctx), ``)
    if (config.tapDances?.length)
        lines.push(...emitTapDances(config.tapDances, ctx), ``)
    if (config.modMorphs?.length)
        lines.push(...emitModMorphs(config.modMorphs, ctx), ``)
    if (config.holdTaps?.length)
        lines.push(...emitHoldTapDefs(config.holdTaps), ``)

    // Encoders: build sensor-rotate behavior nodes (non-keypress pairs) up front,
    // then reference them per layer below.
    const encoders = emitEncoderSensors(config, ctx)
    if (encoders.behaviorLines.length) {
        lines.push(`    behaviors {`, ...encoders.behaviorLines, `    };`, ``)
    }

    // Sliders: analog input has no ZMK keymap behavior — emit the captured
    // value-map as a guidance block (board-side wiring stays manual).
    lines.push(...emitSliderInputs(config, ctx))

    // combos
    if (config.combos?.length) {
        lines.push(`    combos {`)
        lines.push(`        compatible = "zmk,combos";`)
        config.combos.forEach((c, ci) => {
            const binding = emitBinding(c.action, ctx, ['combos', ci, 'action'])
            const layersAttr = c.layers?.length
                ? `\n            layers = <${c.layers.map((n) => ctx.layerIndex.get(n) ?? 0).join(' ')}>;`
                : ''
            lines.push(`        combo_${sanitize(c.name)} {`)
            if (c.timeoutMs !== undefined)
                lines.push(`            timeout-ms = <${c.timeoutMs}>;`)
            lines.push(`            key-positions = <${c.keys.join(' ')}>;`)
            lines.push(`            bindings = <${binding}>;${layersAttr}`)
            lines.push(`        };`)
        })
        lines.push(`    };`)
        lines.push(``)
    }

    // conditional layers
    if (config.conditionalLayers?.length) {
        const idx = (name: string): number => {
            const i = ctx.layerIndex.get(name)
            if (i === undefined) {
                diag.error(`unknown layer "${name}"`, ['conditionalLayers'])
                return 0
            }
            return i
        }
        lines.push(`    conditional_layers {`)
        lines.push(`        compatible = "zmk,conditional-layers";`)
        config.conditionalLayers.forEach((cl, ci) => {
            lines.push(`        cond_${ci} {`)
            lines.push(
                `            if-layers = <${cl.ifLayers.map(idx).join(' ')}>;`,
            )
            lines.push(`            then-layer = <${idx(cl.thenLayer)}>;`)
            lines.push(`        };`)
        })
        lines.push(`    };`)
        lines.push(``)
    }

    // keymap
    lines.push(`    keymap {`)
    lines.push(`        compatible = "zmk,keymap";`)
    config.layers.forEach((layer, li) => {
        const cells = layer.bindings.map((b, bi) =>
            emitBinding(b, ctx, ['layers', li, 'bindings', bi]),
        )
        const wrapped: string[] = []
        for (let i = 0; i < cells.length; i += 6) {
            wrapped.push('                ' + cells.slice(i, i + 6).join(' '))
        }
        lines.push(`        layer_${sanitize(layer.name)} {`)
        lines.push(`            display-name = "${dtsString(layer.name)}";`)
        lines.push(`            bindings = <`)
        lines.push(wrapped.join('\n'))
        lines.push(`            >;`)
        // encoders -> sensor-bindings (inc_dec_kp for keypress pairs, generated
        // sensor-rotate nodes for anything else — see emitEncoderSensors)
        const sensorBindings = encoders.byLayer.get(li)
        if (sensorBindings) {
            lines.push(`            sensor-bindings = <${sensorBindings}>;`)
        }
        lines.push(`        };`)
    })
    lines.push(`    };`)

    // Hold-tap nodes generated for custom-flavor/timing tap_holds above. Emitted
    // after the keymap (devicetree resolves the &ht_N labels regardless of order).
    if (ctx.genHoldTaps.size) {
        lines.push(``)
        lines.push(`    behaviors {`)
        for (const g of ctx.genHoldTaps.values()) lines.push(...g.lines)
        lines.push(`    };`)
    }

    lines.push(`};`)
    lines.push(``)

    const keymapFile: ExportedFile = {
        filename: `${sanitize(config.keyboard.id || config.keyboard.name)}.keymap`,
        mime: 'text/plain',
        content: lines.join('\n'),
    }
    return [
        keymapFile,
        ...(config.keyboard.split
            ? emitSplitOverlay(config, diag)
            : [emitOverlay(config, diag)]),
    ]
}

export const zmkCompiler: KeymapCompiler = {
    target: 'zmk',
    compile: (config) => runCompile(config, emitKeymap),
}

registerCompiler(zmkCompiler)
